// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ayam/ayam.proto

package ayam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AyamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AyamId        int64                  `protobuf:"varint,1,opt,name=ayam_id,json=ayamId,proto3" json:"ayam_id,omitempty"`
	AyamName      string                 `protobuf:"bytes,2,opt,name=ayam_name,json=ayamName,proto3" json:"ayam_name,omitempty"`
	AyamHeight    float32                `protobuf:"fixed32,3,opt,name=ayam_height,json=ayamHeight,proto3" json:"ayam_height,omitempty"`
	AyamWeight    float32                `protobuf:"fixed32,4,opt,name=ayam_weight,json=ayamWeight,proto3" json:"ayam_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AyamRequest) Reset() {
	*x = AyamRequest{}
	mi := &file_ayam_ayam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AyamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AyamRequest) ProtoMessage() {}

func (x *AyamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ayam_ayam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AyamRequest.ProtoReflect.Descriptor instead.
func (*AyamRequest) Descriptor() ([]byte, []int) {
	return file_ayam_ayam_proto_rawDescGZIP(), []int{0}
}

func (x *AyamRequest) GetAyamId() int64 {
	if x != nil {
		return x.AyamId
	}
	return 0
}

func (x *AyamRequest) GetAyamName() string {
	if x != nil {
		return x.AyamName
	}
	return ""
}

func (x *AyamRequest) GetAyamHeight() float32 {
	if x != nil {
		return x.AyamHeight
	}
	return 0
}

func (x *AyamRequest) GetAyamWeight() float32 {
	if x != nil {
		return x.AyamWeight
	}
	return 0
}

type AyamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AyamId        int64                  `protobuf:"varint,1,opt,name=ayam_id,json=ayamId,proto3" json:"ayam_id,omitempty"`
	AyamName      string                 `protobuf:"bytes,2,opt,name=ayam_name,json=ayamName,proto3" json:"ayam_name,omitempty"`
	AyamPrice     float32                `protobuf:"fixed32,3,opt,name=ayam_price,json=ayamPrice,proto3" json:"ayam_price,omitempty"`
	AyamNumber    int64                  `protobuf:"varint,4,opt,name=ayam_number,json=ayamNumber,proto3" json:"ayam_number,omitempty"`
	AyamTotal     int64                  `protobuf:"varint,5,opt,name=ayam_total,json=ayamTotal,proto3" json:"ayam_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AyamResponse) Reset() {
	*x = AyamResponse{}
	mi := &file_ayam_ayam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AyamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AyamResponse) ProtoMessage() {}

func (x *AyamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ayam_ayam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AyamResponse.ProtoReflect.Descriptor instead.
func (*AyamResponse) Descriptor() ([]byte, []int) {
	return file_ayam_ayam_proto_rawDescGZIP(), []int{1}
}

func (x *AyamResponse) GetAyamId() int64 {
	if x != nil {
		return x.AyamId
	}
	return 0
}

func (x *AyamResponse) GetAyamName() string {
	if x != nil {
		return x.AyamName
	}
	return ""
}

func (x *AyamResponse) GetAyamPrice() float32 {
	if x != nil {
		return x.AyamPrice
	}
	return 0
}

func (x *AyamResponse) GetAyamNumber() int64 {
	if x != nil {
		return x.AyamNumber
	}
	return 0
}

func (x *AyamResponse) GetAyamTotal() int64 {
	if x != nil {
		return x.AyamTotal
	}
	return 0
}

type AyamListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AyamResponse        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AyamListResponse) Reset() {
	*x = AyamListResponse{}
	mi := &file_ayam_ayam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AyamListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AyamListResponse) ProtoMessage() {}

func (x *AyamListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ayam_ayam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AyamListResponse.ProtoReflect.Descriptor instead.
func (*AyamListResponse) Descriptor() ([]byte, []int) {
	return file_ayam_ayam_proto_rawDescGZIP(), []int{2}
}

func (x *AyamListResponse) GetItems() []*AyamResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_ayam_ayam_proto protoreflect.FileDescriptor

const file_ayam_ayam_proto_rawDesc = "" +
	"\n" +
	"\x0fayam/ayam.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x01\n" +
	"\vAyamRequest\x12\x17\n" +
	"\aayam_id\x18\x01 \x01(\x03R\x06ayamId\x12\x1b\n" +
	"\tayam_name\x18\x02 \x01(\tR\bayamName\x12\x1f\n" +
	"\vayam_height\x18\x03 \x01(\x02R\n" +
	"ayamHeight\x12\x1f\n" +
	"\vayam_weight\x18\x04 \x01(\x02R\n" +
	"ayamWeight\"\xa3\x01\n" +
	"\fAyamResponse\x12\x17\n" +
	"\aayam_id\x18\x01 \x01(\x03R\x06ayamId\x12\x1b\n" +
	"\tayam_name\x18\x02 \x01(\tR\bayamName\x12\x1d\n" +
	"\n" +
	"ayam_price\x18\x03 \x01(\x02R\tayamPrice\x12\x1f\n" +
	"\vayam_number\x18\x04 \x01(\x03R\n" +
	"ayamNumber\x12\x1d\n" +
	"\n" +
	"ayam_total\x18\x05 \x01(\x03R\tayamTotal\"7\n" +
	"\x10AyamListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.AyamResponseR\x05items2\xa8\x01\n" +
	"\x04Ayam\x12.\n" +
	"\rGetAyamByName\x12\f.AyamRequest\x1a\r.AyamResponse\"\x00\x12:\n" +
	"\vGetAyamList\x12\x16.google.protobuf.Empty\x1a\x11.AyamListResponse\"\x00\x124\n" +
	"\n" +
	"CreateAyam\x12\f.AyamRequest\x1a\x16.google.protobuf.Empty\"\x00B9Z7github.com/skyespirates/microservices-proto/golang/ayamb\x06proto3"

var (
	file_ayam_ayam_proto_rawDescOnce sync.Once
	file_ayam_ayam_proto_rawDescData []byte
)

func file_ayam_ayam_proto_rawDescGZIP() []byte {
	file_ayam_ayam_proto_rawDescOnce.Do(func() {
		file_ayam_ayam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ayam_ayam_proto_rawDesc), len(file_ayam_ayam_proto_rawDesc)))
	})
	return file_ayam_ayam_proto_rawDescData
}

var file_ayam_ayam_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ayam_ayam_proto_goTypes = []any{
	(*AyamRequest)(nil),      // 0: AyamRequest
	(*AyamResponse)(nil),     // 1: AyamResponse
	(*AyamListResponse)(nil), // 2: AyamListResponse
	(*emptypb.Empty)(nil),    // 3: google.protobuf.Empty
}
var file_ayam_ayam_proto_depIdxs = []int32{
	1, // 0: AyamListResponse.items:type_name -> AyamResponse
	0, // 1: Ayam.GetAyamByName:input_type -> AyamRequest
	3, // 2: Ayam.GetAyamList:input_type -> google.protobuf.Empty
	0, // 3: Ayam.CreateAyam:input_type -> AyamRequest
	1, // 4: Ayam.GetAyamByName:output_type -> AyamResponse
	2, // 5: Ayam.GetAyamList:output_type -> AyamListResponse
	3, // 6: Ayam.CreateAyam:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ayam_ayam_proto_init() }
func file_ayam_ayam_proto_init() {
	if File_ayam_ayam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ayam_ayam_proto_rawDesc), len(file_ayam_ayam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ayam_ayam_proto_goTypes,
		DependencyIndexes: file_ayam_ayam_proto_depIdxs,
		MessageInfos:      file_ayam_ayam_proto_msgTypes,
	}.Build()
	File_ayam_ayam_proto = out.File
	file_ayam_ayam_proto_goTypes = nil
	file_ayam_ayam_proto_depIdxs = nil
}
