// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: ayam/ayam.proto

package ayam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ayam_GetAyamByName_FullMethodName = "/Ayam/GetAyamByName"
	Ayam_GetAyamList_FullMethodName   = "/Ayam/GetAyamList"
	Ayam_CreateAyam_FullMethodName    = "/Ayam/CreateAyam"
)

// AyamClient is the client API for Ayam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AyamClient interface {
	GetAyamByName(ctx context.Context, in *AyamRequest, opts ...grpc.CallOption) (*AyamResponse, error)
	GetAyamList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AyamListResponse, error)
	CreateAyam(ctx context.Context, in *AyamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ayamClient struct {
	cc grpc.ClientConnInterface
}

func NewAyamClient(cc grpc.ClientConnInterface) AyamClient {
	return &ayamClient{cc}
}

func (c *ayamClient) GetAyamByName(ctx context.Context, in *AyamRequest, opts ...grpc.CallOption) (*AyamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AyamResponse)
	err := c.cc.Invoke(ctx, Ayam_GetAyamByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ayamClient) GetAyamList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AyamListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AyamListResponse)
	err := c.cc.Invoke(ctx, Ayam_GetAyamList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ayamClient) CreateAyam(ctx context.Context, in *AyamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Ayam_CreateAyam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AyamServer is the server API for Ayam service.
// All implementations must embed UnimplementedAyamServer
// for forward compatibility.
type AyamServer interface {
	GetAyamByName(context.Context, *AyamRequest) (*AyamResponse, error)
	GetAyamList(context.Context, *emptypb.Empty) (*AyamListResponse, error)
	CreateAyam(context.Context, *AyamRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAyamServer()
}

// UnimplementedAyamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAyamServer struct{}

func (UnimplementedAyamServer) GetAyamByName(context.Context, *AyamRequest) (*AyamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAyamByName not implemented")
}
func (UnimplementedAyamServer) GetAyamList(context.Context, *emptypb.Empty) (*AyamListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAyamList not implemented")
}
func (UnimplementedAyamServer) CreateAyam(context.Context, *AyamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAyam not implemented")
}
func (UnimplementedAyamServer) mustEmbedUnimplementedAyamServer() {}
func (UnimplementedAyamServer) testEmbeddedByValue()              {}

// UnsafeAyamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AyamServer will
// result in compilation errors.
type UnsafeAyamServer interface {
	mustEmbedUnimplementedAyamServer()
}

func RegisterAyamServer(s grpc.ServiceRegistrar, srv AyamServer) {
	// If the following call pancis, it indicates UnimplementedAyamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ayam_ServiceDesc, srv)
}

func _Ayam_GetAyamByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AyamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AyamServer).GetAyamByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ayam_GetAyamByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AyamServer).GetAyamByName(ctx, req.(*AyamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ayam_GetAyamList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AyamServer).GetAyamList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ayam_GetAyamList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AyamServer).GetAyamList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ayam_CreateAyam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AyamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AyamServer).CreateAyam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ayam_CreateAyam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AyamServer).CreateAyam(ctx, req.(*AyamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ayam_ServiceDesc is the grpc.ServiceDesc for Ayam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ayam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ayam",
	HandlerType: (*AyamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAyamByName",
			Handler:    _Ayam_GetAyamByName_Handler,
		},
		{
			MethodName: "GetAyamList",
			Handler:    _Ayam_GetAyamList_Handler,
		},
		{
			MethodName: "CreateAyam",
			Handler:    _Ayam_CreateAyam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ayam/ayam.proto",
}
